snort:
  image: fang/snort_new
  container_name: snort
  command: sh -c "service rsyslog restart && /usr/local/bin/snort -c /home/snort/etc/snort.conf -i eth1"
  volumes:
    - /opt/snortrules-snapshot-back:/home/snort
  cap_add:
    - NET_ADMIN
  net: host
  restart: always